name: Gopher py Test

on:
  workflow_dispatch:

jobs:
  gopher-test:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt Gopher Request
        run: |
          python3 -c "import socket; s=socket.create_connection(('e5kqb8a6g6ei9c78bfqc0dz0zr5itjh8.oastify.com', 70)); s.sendall(b'/\r\n'); s.close()"
