name: Gopher SSRF Test

on:
  workflow_dispatch:

jobs:
  gopher-test:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt Gopher Request
        run: |
          curl gopher://468gcybwhwf8a28yc5r2130q0h68u7iw.oastify.com
